-- Baseline schema for hitorro-fleet-mail-analytics.
-- SQL:2003 identity + TEXT + quoted reserved names → runs unchanged on
-- H2 (MODE=PostgreSQL) and Postgres.

CREATE TABLE watermark (
    source_id                VARCHAR(128) PRIMARY KEY,
    last_row_id              BIGINT,
    last_uid                 BIGINT,
    last_uidvalidity         BIGINT,
    last_run_at              TIMESTAMP,
    backfill_horizon_at      TIMESTAMP,
    backfill_complete        BOOLEAN NOT NULL DEFAULT FALSE,
    total_ingested           BIGINT NOT NULL DEFAULT 0,
    last_error               VARCHAR(2000)
);

CREATE TABLE saved_query (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(255) NOT NULL,
    description              VARCHAR(2000),
    dsl_json                 TEXT NOT NULL,
    tags                     VARCHAR(1000),
    owner                    VARCHAR(255),
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL
);
CREATE INDEX idx_saved_query_name ON saved_query(name);

CREATE TABLE alert_rule (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_query_id           BIGINT NOT NULL,
    name                     VARCHAR(255) NOT NULL,
    cron                     VARCHAR(120) NOT NULL,
    delta_mode               VARCHAR(64) NOT NULL,
    threshold_config_json    TEXT,
    delivery_channels_json   TEXT NOT NULL,
    enabled                  BOOLEAN NOT NULL DEFAULT TRUE,
    cooldown_seconds         INT NOT NULL DEFAULT 0,
    muted_until              TIMESTAMP,
    last_run_at              TIMESTAMP,
    last_fingerprint         VARCHAR(128),
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL,
    CONSTRAINT fk_alert_rule_saved_query FOREIGN KEY (saved_query_id)
        REFERENCES saved_query(id) ON DELETE CASCADE
);
CREATE INDEX idx_alert_rule_enabled ON alert_rule(enabled);

CREATE TABLE alert_firing (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id            BIGINT NOT NULL,
    fired_at                 TIMESTAMP NOT NULL,
    fingerprint              VARCHAR(128),
    result_summary_json      TEXT,
    matched_doc_ids_json     TEXT,
    CONSTRAINT fk_alert_firing_rule FOREIGN KEY (alert_rule_id)
        REFERENCES alert_rule(id) ON DELETE CASCADE
);
CREATE INDEX idx_alert_firing_rule_time ON alert_firing(alert_rule_id, fired_at);

CREATE TABLE alert_delivery (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firing_id                BIGINT NOT NULL,
    channel                  VARCHAR(64) NOT NULL,
    target                   VARCHAR(500),
    status                   VARCHAR(32) NOT NULL,
    attempts                 INT NOT NULL DEFAULT 0,
    last_error               VARCHAR(2000),
    delivered_at             TIMESTAMP,
    CONSTRAINT fk_alert_delivery_firing FOREIGN KEY (firing_id)
        REFERENCES alert_firing(id) ON DELETE CASCADE
);
CREATE INDEX idx_alert_delivery_status ON alert_delivery(status);

CREATE TABLE inbox_item (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firing_id                BIGINT,
    title                    VARCHAR(500) NOT NULL,
    body_preview             VARCHAR(2000),
    severity                 VARCHAR(32) NOT NULL DEFAULT 'INFO',
    payload_json             TEXT,
    is_read                  BOOLEAN NOT NULL DEFAULT FALSE,
    dismissed                BOOLEAN NOT NULL DEFAULT FALSE,
    snoozed_until            TIMESTAMP,
    created_at               TIMESTAMP NOT NULL,
    CONSTRAINT fk_inbox_item_firing FOREIGN KEY (firing_id)
        REFERENCES alert_firing(id) ON DELETE SET NULL
);
CREATE INDEX idx_inbox_item_state ON inbox_item(is_read, dismissed, snoozed_until);

CREATE TABLE webhook_config (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(255) NOT NULL,
    url                      VARCHAR(1000) NOT NULL,
    secret                   VARCHAR(500),
    headers_json             TEXT,
    enabled                  BOOLEAN NOT NULL DEFAULT TRUE,
    last_success_at          TIMESTAMP,
    last_error               VARCHAR(2000),
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL
);

CREATE TABLE report (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(255) NOT NULL,
    description              VARCHAR(2000),
    kind                     VARCHAR(64) NOT NULL,
    config_json              TEXT NOT NULL,
    cron                     VARCHAR(120),
    retention_days           INT NOT NULL DEFAULT 90,
    enabled                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL
);

CREATE TABLE report_run (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id                BIGINT NOT NULL,
    started_at               TIMESTAMP NOT NULL,
    finished_at              TIMESTAMP,
    status                   VARCHAR(32) NOT NULL,
    artifact_path            VARCHAR(2000),
    artifacts_json           TEXT,
    error_message            VARCHAR(2000),
    CONSTRAINT fk_report_run_report FOREIGN KEY (report_id)
        REFERENCES report(id) ON DELETE CASCADE
);
CREATE INDEX idx_report_run_report_time ON report_run(report_id, started_at);

CREATE TABLE enrichment_suggestion (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                     VARCHAR(64) NOT NULL,
    target_field             VARCHAR(255),
    title                    VARCHAR(500) NOT NULL,
    rationale                VARCHAR(2000),
    evidence_json            TEXT,
    priority                 INT NOT NULL DEFAULT 50,
    status                   VARCHAR(32) NOT NULL DEFAULT 'NEW',
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL
);
CREATE INDEX idx_enrichment_status ON enrichment_suggestion(status, priority);

CREATE TABLE query_audit (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path                     VARCHAR(500) NOT NULL,
    query_json               TEXT,
    latency_ms               INT,
    result_count             BIGINT,
    caller                   VARCHAR(255),
    recorded_at              TIMESTAMP NOT NULL
);
CREATE INDEX idx_query_audit_at ON query_audit(recorded_at);
CREATE INDEX idx_query_audit_path ON query_audit(path);
